# Generated by Django 6.0.4 on 2026-04-30 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('College', 'College'), ('Basic Education', 'Basic Education')], default='College', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.program'),
        ),
        migrations.AddField(
            model_name='subject',
            name='year_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
