# Generated by Django 6.0.4 on 2026-04-21 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('room', models.CharField(max_length=50)),
                ('days', models.CharField(blank=True, default='TBA', max_length=100, null=True)),
                ('days_of_week', models.CharField(blank=True, help_text='e.g., M-W-F or T-Th', max_length=50, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('schedule_text', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicterm')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.CharField(blank=True, max_length=20, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.classschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_logged', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='GradingComponent',
            fields=[
                ('component_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('weight_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.classschedule')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('assessment_type', models.CharField(choices=[('Quiz', 'Quiz'), ('Activity', 'Activity'), ('Exam', 'Exam'), ('Project', 'Project')], default='Activity', max_length=20)),
                ('total_points', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('date_given', models.DateField(blank=True, null=True)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.period')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.gradingcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='GradingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('transmutation_base', models.IntegerField(choices=[(0, 'Base 0 (Straight Percentage)'), (50, 'Base 50 (Standard K-12)'), (60, 'Base 60 (College Standard)')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='classschedule',
            name='grading_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.gradingtemplate'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.assessment')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.period')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='grading.gradingtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodGrade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('computed_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_grades', to='grading.enrollment')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.period')),
            ],
            options={
                'unique_together': {('enrollment', 'period')},
            },
        ),
    ]
