# Generated by Django 6.0.4 on 2026-04-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('Quiz', 'Quiz'), ('Activity', 'Activity'), ('Exam', 'Exam'), ('Project', 'Project'), ('Recitation', 'Recitation'), ('Attendance', 'Attendance')], default='Activity', max_length=20),
        ),
    ]
