# Generated by Django 6.0.4 on 2026-04-30 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('grading', '0002_alter_assessment_assessment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingcomponent',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.period'),
        ),
    ]
