# Generated by Django 6.0.4 on 2026-05-01 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_program_program_type_subject_program_and_more'),
        ('grading', '0003_gradingcomponent_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.period'),
        ),
    ]
